/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.dorongold.task-tree") version "4.0.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


tasks.named<JavaCompile>("compileJava") {
    options.isDebug = false
}


abstract class HelloTask : DefaultTask() {
    @get:OutputFile
    abstract val outputFile: RegularFileProperty
    @get:Input
    abstract val str: Property<String>
    init{
        str.convention("Hello World!")
    }
    @TaskAction
    fun action(){
        println(str.get())
        val outFile = outputFile.get().asFile
        outFile.createNewFile()
        outFile.writeText(str.get())
    }
}

tasks.register<HelloTask>("hello") {
    str = "Hello Kotlin!"
    outputFile = layout.buildDirectory.file("hello.txt")

    doFirst {
        println("doFirst: Hello from HelloTask!")
    }
    doLast {
        println("doLast: Bye from HelloTask!")
    }
}

tasks.register<Zip>("ZipTestResults") {
    //dependsOn("test")
    archiveFileName = "test-results.zip"
    destinationDirectory = layout.buildDirectory
    //from(layout.buildDirectory.dir("test-results"))
    from(tasks.named("test"))
    include("**/*.xml")
}

tasks.named("test") {
    finalizedBy("ZipTestResults")
}

tasks.named("ZipTestResults") {
    description = "Zips the test results into a single file"
    group = "distribution"
}

tasks.named("hello") {
    description = "Prints a greeting message to the console"
    group = "help"
}

tasks.register("registerTask") {
    println("registerTask!")
}

tasks.create("createTask"){
    println("createTask!")
}

task("eagerTask") {
    println("eagerTask!")
}


tasks.register<PrintString>("printString"){
    str = "Im printing a string"
}